on: [pull_request]
name: Free Code Coverage Action - UPLOAD
jobs:
  UPLOAD:
    runs-on: ubuntu-latest
    steps:
      - uses: SamuelCabralCruz/free-code-coverage/upload@v0.0.13
        with:
          bucket-name: code-grind-coverage
          project-name: math-utils
          coverage-metric: 90
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
